version = 1

[[annotations]]
path = ["**/*.md", "**/*.json", "requirements.txt", "Pipfile*", ".azure-pipelines/*", "logo/*.png", "logo/logo_base64.txt",".env.example"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Observes io LTD"
SPDX-License-Identifier = "LicenseRef-PolyForm-Internal-Use-1.0.0"

