#### Copyright Notice
# SPDX-FileCopyrightText: 2025 Observes io LTD
# SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0
#
# Copyright (c) 2025 Observes io LTD, Scotland, Company No. SC864704
# Licensed under PolyForm Internal Use 1.0.0, see LICENSE or https://polyformproject.org/licenses/internal-use/1.0.0
# Internal use only; additional clarifications in LICENSE-CLARIFICATIONS.md
####

trigger: none

pool:
  # Azure public agents have time out of 60 min by default can go up to 360 minutes
  vmImage: ubuntu-latest

jobs:
- job: observesScan
  timeoutInMinutes: 360
  steps:
  - task: observes@1
    timeoutInMinutes: 360
    inputs:
      serviceConnection: 'my-observes-service-connection'