#### Copyright Notice
# SPDX-FileCopyrightText: 2025 Observes io LTD
# SPDX-License-Identifier: LicenseRef-PolyForm-Internal-Use-1.0.0
#
# Copyright (c) 2025 Observes io LTD, Scotland, Company No. SC864704
# Licensed under PolyForm Internal Use 1.0.0, see LICENSE or https://polyformproject.org/licenses/internal-use/1.0.0
# Internal use only; additional clarifications in LICENSE-CLARIFICATIONS.md
####

trigger: none

pool:
  vmImage: 'ubuntu-latest'


jobs:
- job: observesScan
  timeoutInMinutes: 360
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - task: CmdLine@2
    displayName: 'Set up Python environment'
    inputs:
      script: |
        git clone https://github.com/observes-io/observes-scanner.git
        cd observes-scanner
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt || true
  - task: CmdLine@2
    displayName: 'Run Azure DevOps Scanner'
    inputs:
      script: |
        source .venv/bin/activate
        python scan.py --organization <YourOrganization> --job-id $(Build.BuildId) --pat-token <YourPATToken> --results-dir $(Build.ArtifactStagingDirectory)
      #env:
      #  AZURE_DEVOPS_PAT: <YourPATToken> can do environment variable instead of command line for PAT tokens
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'scan-results'
      publishLocation: 'Container'

